[package]
name = "simple_lcd"
version = "0.1.0"
edition = "2021"

[dependencies]
# RP2040 / HAL stuff
rp-pico = "0.9"
embedded-hal = "0.2"
gc9a01a = "0.1.1"
# embedded-graphics 0.7
embedded-graphics = "0.7.1"

# st7789 0.7.0 for e-g 0.7, with the "graphics" feature
st7789 = { version = "0.7.0", features = ["graphics"] }

# For the SPI display interface
display-interface-spi = "0.4"

# Etc.
panic-halt = "0.2"
fugit = "0.3"
cortex-m-rt = "0.7"
cortex-m = "0.7"