[package]
name = "lilbud"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = { version = "0.2.7", features = ["unproven"] }
display-interface-spi = "0.4.1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
embedded-graphics = "0.8.0"
rp-pico = "0.9"
fugit = "0.3"
gc9a01a = "0.1.1"
heapless = "0.8.0"
rand = { version = "0.8", default-features = false }
rand_xorshift = "0.3"
rand_core = { version = "0.6", default-features = false }
