#!/usr/bin/env python3
"""
Preprocesses faces.ndjson into src/face_data.rs — static Rust arrays,
no runtime deserialization needed on embedded.

Usage: python3 gen_faces.py faces.ndjson > src/face_data.rs
"""
import json, sys

KEYS = list("abcdefghijklmnopqr")  # 18 face points

faces = []
for line in open(sys.argv[1]):
    line = line.strip()
    if not line:
        continue
    try:
        obj = json.loads(line)
        pts = obj["message"]["points"]
        face = []
        for k in KEYS:
            p = pts[k]
            x = int(p["x"]) // 2 + 50
            y = int(p["y"]) // 2 + 50
            face.append((x, y))
        faces.append(face)
    except (KeyError, ValueError, json.JSONDecodeError):
        continue

print("// Auto-generated by gen_faces.py — do not edit manually.")
print("// Point order: a=0 b=1 c=2 d=3 e=4 f=5 g=6 h=7 i=8 j=9 k=10 l=11 m=12 n=13 o=14 p=15 q=16 r=17")
print(f"pub static FACE_DATA: &[[(i32, i32); 18]] = &[")
for face in faces:
    coords = ", ".join(f"({x},{y})" for x, y in face)
    print(f"    [{coords}],")
print("];")
