#!/usr/bin/env bun
/**
 * Preprocesses faces.ndjson into:
 *   src/face_data.rs          — static Rust arrays (no runtime deserialization)
 *   dock-ui/src/face-fixtures.ts — typed TS arrays for dock-ui tests
 *
 * Usage: bun run gen_faces.ts <faces.ndjson>
 *
 * Coordinate transform: x = floor(raw_x / 2 + 50), y = floor(raw_y / 2 + 50)
 */

import { join } from 'path'

const KEYS = [...'abcdefghijklmnopqr']  // 18 face points, in order

const ndjsonPath = process.argv[2]
if (!ndjsonPath) {
  console.error('Usage: bun run gen_faces.ts <faces.ndjson>')
  process.exit(1)
}

const scriptDir = import.meta.dir

interface Face {
  emo: string
  pts: number[]  // flat [x0,y0, x1,y1, ...] — 36 values
}

const faces: Face[] = []

for (const line of (await Bun.file(ndjsonPath).text()).split('\n')) {
  if (!line.trim()) continue
  try {
    const obj = JSON.parse(line)
    const pts_raw = obj.message.points
    const emo: string = obj.message.emo ?? 'unknown'
    const pts: number[] = []
    for (const k of KEYS) {
      const p = pts_raw[k]
      pts.push(Math.floor(Number(p.x) / 2 + 50))
      pts.push(Math.floor(Number(p.y) / 2 + 50))
    }
    faces.push({ emo, pts })
  } catch {
    continue
  }
}

if (faces.length === 0) {
  console.error('No faces parsed — check input file format')
  process.exit(1)
}

// ── src/face_data.rs ──────────────────────────────────────────────────────────

function rsPairs(pts: number[]): string {
  const pairs: string[] = []
  for (let i = 0; i < pts.length; i += 2) pairs.push(`(${pts[i]},${pts[i+1]})`)
  return pairs.join(', ')
}

const rs = [
  '// Auto-generated by gen_faces.ts — do not edit manually.',
  '// Point order: a=0 b=1 c=2 d=3 e=4 f=5 g=6 h=7 i=8 j=9 k=10 l=11 m=12 n=13 o=14 p=15 q=16 r=17',
  'pub static FACE_DATA: &[[(i32, i32); 18]] = &[',
  ...faces.map(({ pts }) => `    [${rsPairs(pts)}],`),
  '];',
  '',
  'pub static FACE_EMOS: &[&str] = &[',
  ...faces.map(({ emo }) => `    "${emo}",`),
  '];',
  '',
].join('\n')

await Bun.write(join(scriptDir, 'src/face_data.rs'), rs)

// ── dock-ui/src/face-fixtures.ts ──────────────────────────────────────────────

const ts = [
  '// Auto-generated by gen_faces.ts — do not edit manually.',
  '// Point order: a=0 b=1 c=2 d=3 e=4 f=5 g=6 h=7 i=8 j=9 k=10 l=11 m=12 n=13 o=14 p=15 q=16 r=17',
  '',
  '// All faces as flat [x0,y0, x1,y1, ...] arrays (36 values each)',
  'export const FACES: number[][] = [',
  ...faces.map(({ pts, emo }) => `  [${pts.join(', ')}], // ${emo}`),
  ']',
  '',
  '// One face per emotion name (last entry wins for duplicates)',
  'export const FACE_BY_EMO: Record<string, number[]> = {',
  ...faces.map(({ emo, pts }) => `  ${JSON.stringify(emo)}: [${pts.join(', ')}],`),
  '}',
  '',
].join('\n')

await Bun.write(join(scriptDir, 'dock-ui/src/face-fixtures.ts'), ts)

console.log(`Generated ${faces.length} faces`)
console.log(`  → src/face_data.rs`)
console.log(`  → dock-ui/src/face-fixtures.ts`)
